language: node_js
node_js:
  - "6.1"
install:
  - "npm install"
test:
  - "npm test"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24d3bd39903d3e0c977e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
